### ISSUE TITLE
Doesn't work on newer exe

### ISSUE THREAD

**Issue by pnill** [RexProg/ILProtectorUnpacker#1]
Gave it a shot and sadly doesn't seem to work on a specific newer exe, not sure of the Protector version being used.

[+] Wait...
[!] Exception :
Object reference not set to an instance of an object.
[!] Press key to exit...

**Comment by pnill** [comment]
Looking at the Protect dlls bundled into the application it appears to be the exact version you were intending to support:
000B7509  ILProtector
000B7522  $b96add98-ece2-4312-947e-aef0e6ec5d0b
000B754B  PVgrSoft
000B7559  2.0.21.9

**Comment by pnill** [comment]
Seems for some reason method is null here:
https://github.com/RexProg/ILProtectorUnpacker/blob/master/ILProtectorUnpacker.cs#L145

Every method is null actually when operating against this executable; trying to debug it to see where I'm going wrong never dealt with ILProtect before now personally, and also don't deal with .net too much either.

**Comment by pnill** [comment]
Doing some additional research/debugging I think I understand what's supposed to happen just don't understand why it's not yet.

I'm guessing that method is supposed to contain the actual pointer to the real method that's going to be executed by the invoke being executed in the application.

So where the application resolves the pointer to a method by doing an invoke on a specific method the idea is that the application unpacks by doing the same thing but resolves it and updates it?

UPDATE: Stepped through it an can't really follow the invoke to gather the actual method address, I know this is certainly what's being attempted at this point but not sure why the method is returning null.

It's a 64bit application I'm trying to unpack I'm wondering if that makes a difference, has this unpacker been tested with with 64bit packed/protected files yet?

**Comment by RexProg** [comment]
Hi man
Forgive me for a delay(I had a busy week)
can you send your target to me? (RexProg.Programmer@gmail.com)

**Comment by pnill** [comment]
Its a bit large I'll upload it some where.

**Comment by RexProg** [comment]
A DLL is not at the side of the program, while Unpacker is working on the program, it receives the IO exception and return null as you said.
pasteboard.co/GYXet4f.png
Put the dll next to the program so your problem will be resolved
