### ISSUE TITLE
Error: Object reference not set to an instance of an object. iLProtector V2.0.22.4

### ISSUE THREAD

**Issue by ghost** [RexProg/ILProtectorUnpacker#5]
Hey Firstly Thank you for really great contribution in RE field.
I would really love to know if you could do something for iLProtector V2.0.22.4

*********************************
***                           ***
***    ILProtector Unpacker   ***
***     Coded By RexProg      ***
***                           ***
*********************************
[?] Enter Your Program Path :
C:\Users\Work\Desktop\Script.exe
[+] Wait...
[!] Exception :
Object reference not set to an instance of an object.
[!] Press key to exit...

**Comment by ghost** [comment]
That was the external DLL issue, While With DLL its Says
[+] Wait...
[!] Exception :
Exception has been thrown by the target of an invocation.
[!] Press key to exit...

**Comment by RexProg** [comment]
Send your target to RexProg.Programmer@gmail.com

**Comment by ghost** [comment]
Its in your inbox sir.
