### ISSUE TITLE
Didn't works with new version of ILProtector

### ISSUE THREAD

**Issue by simpleperson123** [RexProg/ILProtectorUnpacker#9]
I tried to unpack .net exe protected by newest version of ILProtectror with this program and it didn't worked. It throw this error: (Error in Read() Value of object cannot be NULL).

**Comment by tanu360** [comment]
Agreed. It dont support latest version 2.0.22.9 I was trying to unpack a Malware packed with IL Protection but unable to do so.

**Comment by yokrysty** [comment]
updated
